### ISSUE TITLE
CubeControl error Java Compiling

### ISSUE THREAD

**Issue by ghost** [xythobuz/LED-Cube#33]
Java version : 1.8.0_121
OS : Win7 64bit

Note : ./Frame.java uses unchecked or unsafe operations
Note : Recompile with -Xlint:unchecked for details

**Comment by xythobuz** [comment]
Could you be a little more specific? I don't have a Windows machine to test here, but on macOS with Java 1.8 I get the same messages, but they are not error messages, only warnings! CubeControl compiles flawlessly and runs.

**Comment by ghost** [comment]
Now i have created the CubeControl.jar
but when i run it, it suddenly close

when i start to run
java -jar CubeControl.jar

it shows
libpng warning: iCCP: known incorrect sRGB profile
Error : Could not find or load main class Frame

and apps suddenly closed

**Comment by ghost** [comment]
This is my CubeControlWin.jar in Rar archive
![image](https://cloud.githubusercontent.com/assets/26142549/23533865/cab1a528-ffe6-11e6-8661-c56d67ddd9e6.png)

**Comment by ghost** [comment]
#Update
I have compiled the CubeControl.jar but when i try to run it with :
java -jar CubeControl.jar

it prompt :
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: javax/media/j3d/Canvas3D
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: javax.media.j3d.Canvas3D
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

Do this program run on 64bit system?
I'm now using Ubuntu 16.04 (64bit) with java1.8.0_121

**Comment by xythobuz** [comment]
CubeControl depends on Java3D. [Maybe try this package](https://launchpad.net/ubuntu/xenial/+source/java3d)...

**Comment by ghost** [comment]
Unfortunately, i've done installing all of those packages :)

**Comment by xythobuz** [comment]
Alright, I've got a [premade 64bit Ubuntu 16.04.2 VirtualBox image](http://www.osboxes.org/ubuntu/) and tried it myself. The problem for me was the default installation path for the Java3D package:

    sudo apt-get install build-essential git default-jdk libjava3d-java
    
    sudo cp /usr/lib/jni/libj3dcore-ogl.so /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/
    sudo cp /usr/share/java/j3d*.jar /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/
    sudo cp /usr/share/java/vecmath*.jar /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/
    
    git clone https://github.com/xythobuz/LED-Cube.git
    cd LED-Cube/CubeControl
    
    vim libSerial/makefile # Change HEADERPATH to java-8-openjdk-amd64
    
    make
    java -jar CubeControlLinux.jar

And it works that way. So make sure to fix the jar and library paths! It's not a problem with 64bit machines and also not really CubeControls fault... :smile:

![2017-03-15_163052](https://cloud.githubusercontent.com/assets/557828/23956424/e3e8fb12-099c-11e7-8f64-26723a0e5519.png)

The solution [was found here](https://ubuntuforums.org/showthread.php?t=1105627), by the way...

**Comment by ghost** [comment]
Haha, Thank You Very Much now i'm continuing my project :sweat_smile: 
BTW greeting from Indonesia
![yes](https://cloud.githubusercontent.com/assets/26142549/23966495/2228a8a4-09ee-11e7-847e-6c2d5364eeb0.png)
